# -*- coding: utf-8 -*-
"""Xlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19FfXomo3kXIs8Imx8OJvoDhmDBNwHT_V
"""

from indic_transliteration import sanscript
from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate

data = input("Enter a string in Hinglish:")

print(transliterate(data, sanscript.ITRANS, sanscript.DEVANAGARI))